:revnumber: 1.0

include::header.adoc[]

= RFC 792


////
Network Working Group                                          J. Postel
Request for Comments:  792                                           ISI
                                                          September 1981
Updates:  RFCs 777, 760
Updates:  IENs 109, 128
////


[frame=none, cols="<,>", width="99%"]
|===
| Network Working Group +
Request for Comments:  792

| INTERNET STANDARD +
Errata Exist +
 J. Postel +
ISI +
September 1981

| Updates:  RFCs 777, 760 +
Updates:  IENs 109, 128
|

|===

[frame=none, cols="^", width="99%"]
|===
|                  INTERNET CONTROL MESSAGE PROTOCOL +
 +
                         DARPA INTERNET PROGRAM +
                         PROTOCOL SPECIFICATION +
|===


== Introduction

The Internet Protocol (IP) <<ref1>> is used for host-to-host datagram
service in a system of interconnected networks called the
Catenet <<ref2>>.  The network connecting devices are called Gateways.
These gateways communicate between themselves for control purposes
via a Gateway to Gateway Protocol (GGP) <<ref3>> <<ref4>>.  Occasionally a
gateway or destination host will communicate with a source host, for
example, to report an error in datagram processing.  For such
purposes this protocol, the Internet Control Message Protocol (ICMP),
is used.  ICMP, uses the basic support of IP as if it were a higher
level protocol, however, ICMP is actually an integral part of IP, and
must be implemented by every IP module.

ICMP messages are sent in several situations:  for example, when a
datagram cannot reach its destination, when the gateway does not have
the buffering capacity to forward a datagram, and when the gateway
can direct the host to send traffic on a shorter route.

The Internet Protocol is not designed to be absolutely reliable.  The
purpose of these control messages is to provide feedback about
problems in the communication environment, not to make IP reliable.
There are still no guarantees that a datagram will be delivered or a
control message will be returned.  Some datagrams may still be
undelivered without any report of their loss.  The higher level
protocols that use IP must implement their own reliability procedures
if reliable communication is required.

The ICMP messages typically report errors in the processing of
datagrams.  To avoid the infinite regress of messages about messages
etc., [[errata_1231]] no ICMP messages are sent about [.rfc-error-text]#ICMP messages#.  [[errata_576]] Also ICMP
messages are only sent about errors in handling fragment zero of
[.rfc-error-text]#fragemented# datagrams.  (Fragment zero has the fragment [.rfc-error-text]#offeset# equal
zero) .

== Message Formats

ICMP messages are sent using the basic IP header.  The first octet of
the data portion of the datagram is a ICMP type field; the value of
this field determines the format of the remaining data.  Any field
labeled "unused" is reserved for later extensions and must be zero
when sent, but receivers should not use these fields (except to
include them in the checksum).  Unless otherwise noted under the
individual format descriptions, the values of the internet header
fields are as follows:

[horizontal]
Version ::
+
4

IHL ::
+
Internet header length in 32-bit words.

Type of Service ::
+
0

Total Length ::
+
Length of internet header and data in octets.

Identification, Flags, Fragment Offset ::
+
Used in fragmentation, see <<ref1>>.

Time to Live ::
+
Time to live in seconds; as this field is decremented at each
machine in which the datagram is processed, the value in this
field should be at least as great as the number of gateways which
this datagram will traverse.

Protocol ::
+
ICMP = 1

Header Checksum ::
+
The 16 bit one's complement of the one's complement sum of all 16
bit words in the header.  For computing the checksum, the checksum
field should be zero.  This checksum may be replaced in the
future.

Source Address ::
+
The address of the gateway or host that composes the ICMP message.
Unless otherwise noted, this can be any of a gateway's addresses.

Destination Address ::
+
The address of the gateway or host to which the message should be
sent.



== Destination Unreachable Message

....
    0                   1                   2                   3
    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |     Type      |     Code      |          Checksum             |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                             unused                            |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |      Internet Header + 64 bits of Original Data Datagram      |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
....


//[horizontal]
IP Fields: ::
+
====
[horizontal]
Destination Address ::
+
The source network and address from the original datagram's data.
====

ICMP Fields: ::
+
====
[horizontal]
Type ::
+
*3*

Code ::
+
0 = net unreachable;
+
1 = host unreachable;
+
2 = protocol unreachable;
+
3 = port unreachable;
+
4 = fragmentation needed and DF set;
+
5 = source route failed.

Checksum ::
+
The checksum is the 16-bit ones's complement of the one's
complement sum of the ICMP message starting with the ICMP Type.
For computing the checksum , the checksum field should be zero.
This checksum may be replaced in the future.

Internet Header + 64 bits of Data Datagram ::
+
The internet header plus the first 64 bits of the original
datagram's data.  This data is used by the host to match the
message to the appropriate process.  If a higher level protocol
uses port numbers, they are assumed to be in the first 64 data
bits of the original datagram's data.

Description ::
+
If, according to the information in the gateway's routing tables,
the network specified in the internet destination field of a
datagram is unreachable, e.g., the distance to the network is
infinity, the gateway may send a destination unreachable message
to the internet source host of the datagram.  In addition, in some
networks, the gateway may be able to determine if the internet
destination host is unreachable.  Gateways in these networks may
send destination unreachable messages to the source host when the
destination host is unreachable.
+
If, in the destination host, the IP module cannot deliver the
datagram  because the indicated protocol module or process port is
not active, the destination host may send a destination
unreachable message to the source host.
+
Another case is when a datagram must be fragmented to be forwarded
by a gateway yet the Don't Fragment flag is on.  In this case the
gateway must discard the datagram and may return a destination
unreachable message.
+
Codes 0, 1, 4, and 5 may be received from a gateway.  Codes 2 and
3 may be received from a host.
====


== Time Exceeded Message

....
    0                   1                   2                   3
    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |     Type      |     Code      |          Checksum             |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                             unused                            |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |      Internet Header + 64 bits of Original Data Datagram      |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
....

IP Fields: ::
+
====
[horizontal]
Destination Address ::
+
The source network and address from the original datagram's data.
====

ICMP Fields: ::
+
====
[horizontal]
Type ::
+
*11*

Code ::
+
0 = time to live exceeded in transit;
+
1 = fragment reassembly time exceeded.

Checksum ::
+
The checksum is the 16-bit ones's complement of the one's
complement sum of the ICMP message starting with the ICMP Type.
For computing the checksum , the checksum field should be zero.
This checksum may be replaced in the future.

Internet Header + 64 bits of Data Datagram ::
+
The internet header plus the first 64 bits of the original
datagram's data.  This data is used by the host to match the
message to the appropriate process.  If a higher level protocol
uses port numbers, they are assumed to be in the first 64 data
bits of the original datagram's data.

Description ::
+
If the gateway processing a datagram finds the time to live field
is zero it must discard the datagram.  The gateway may also notify
the source host via the time exceeded message.
+
If a host reassembling a fragmented datagram cannot complete the
reassembly due to missing fragments within its time limit it
discards the datagram, and it may send a time exceeded message.
+
If fragment zero is not available then no time exceeded need be
sent at all.
+
Code 0 may be received from a gateway.  Code 1 may be received
from a host.
====


== Parameter Problem Message

....
    0                   1                   2                   3
    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |     Type      |     Code      |          Checksum             |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |    Pointer    |                   unused                      |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |      Internet Header + 64 bits of Original Data Datagram      |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
....


IP Fields: ::
+
====
[horizontal]
Destination Address ::
+
The source network and address from the original datagram's data.
====

ICMP Fields: ::
+
====
[horizontal]
Type ::
+
*12*

Code ::
+
0 = pointer indicates the error.

Checksum ::
+
The checksum is the 16-bit ones's complement of the one's
complement sum of the ICMP message starting with the ICMP Type.
For computing the checksum , the checksum field should be zero.
This checksum may be replaced in the future.

Pointer ::
+
If code = 0, identifies the octet where an error was detected.

Internet Header + 64 bits of Data Datagram ::
+
The internet header plus the first 64 bits of the original
datagram's data.  This data is used by the host to match the
message to the appropriate process.  If a higher level protocol
uses port numbers, they are assumed to be in the first 64 data
bits of the original datagram's data.

Description ::
+
If the gateway or host processing a datagram finds a problem with
the header parameters such that it cannot complete processing the
datagram it must discard the datagram.  One potential source of
such a problem is with incorrect arguments in an option.  The
gateway or host may also notify the source host via the parameter
problem message.  This message is only sent if the error caused
the datagram to be discarded.
+
The pointer identifies the octet of the original datagram's header
where the error was detected (it may be in the middle of an
option).  For example, 1 indicates something is wrong with the
Type of Service, and (if there are options present) 20 indicates
something is wrong with the type code of the first option.
+
Code 0 may be received from a gateway or a host.
====


== Source Quench Message

....
    0                   1                   2                   3
    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |     Type      |     Code      |          Checksum             |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                             unused                            |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |      Internet Header + 64 bits of Original Data Datagram      |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
....

IP Fields: ::
+
====
[horizontal]
Destination Address ::
+
The source network and address of the original datagram's data.
====

ICMP Fields: ::
+
====
[horizontal]
Type ::
+
*4*

Code ::
+
0

Checksum ::
+
The checksum is the 16-bit ones's complement of the one's
complement sum of the ICMP message starting with the ICMP Type.
For computing the checksum , the checksum field should be zero.
This checksum may be replaced in the future.

Internet Header + 64 bits of Data Datagram ::
+
The internet header plus the first 64 bits of the original
datagram's data.  This data is used by the host to match the
message to the appropriate process.  If a higher level protocol
uses port numbers, they are assumed to be in the first 64 data
bits of the original datagram's data.

Description ::
+
A gateway may discard internet datagrams if it does not have the
buffer space needed to queue the datagrams for output to the next
network on the route to the destination network.  If a gateway
discards a datagram, it may send a source quench message to the
internet source host of the datagram.  A destination host may also
send a source quench message if datagrams arrive too fast to be
processed.  The source quench message is a request to the host to
cut back the rate at which it is sending traffic to the internet
destination.  The gateway may send a source quench message for
every message that it discards.  On receipt of a source quench
message, the source host should cut back the rate at which it is
sending traffic to the specified destination until it no longer
receives source quench messages from the gateway.  The source host
can then gradually increase the rate at which it sends traffic to
the destination until it again receives source quench messages.
+
The gateway or host may send the source quench message when it
approaches its capacity limit rather than waiting until the
capacity is exceeded.  This means that the data datagram which
triggered the source quench message may be delivered.
+
Code 0 may be received from a gateway or a host.
====


== Redirect Message

....
    0                   1                   2                   3
    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |     Type      |     Code      |          Checksum             |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                 Gateway Internet Address                      |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |      Internet Header + 64 bits of Original Data Datagram      |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
....


IP Fields: ::
+
====
[horizontal]
Destination Address ::
+
The source network and address of the original datagram's data.
====

ICMP Fields: ::
+
====
[horizontal]
Type ::
+
*5*

Code ::
+
0 = Redirect datagrams for the Network.
+
1 = Redirect datagrams for the Host.
+
2 = Redirect datagrams for the Type of Service and Network.
+
3 = Redirect datagrams for the Type of Service and Host.

Checksum ::
+
The checksum is the 16-bit ones's complement of the one's
complement sum of the ICMP message starting with the ICMP Type.
For computing the checksum , the checksum field should be zero.
This checksum may be replaced in the future.

Gateway Internet Address ::
+
Address of the gateway to which traffic for the network specified
in the internet destination network field of the original
datagram's data should be sent.

Internet Header + 64 bits of Data Datagram ::
+
The internet header plus the first 64 bits of the original
datagram's data.  This data is used by the host to match the
message to the appropriate process.  If a higher level protocol
uses port numbers, they are assumed to be in the first 64 data
bits of the original datagram's data.

Description ::
+
The gateway sends a redirect message to a host in the following
situation.  A gateway, G1, receives an internet datagram from a
host on a network to which the gateway is attached.  The gateway,
G1, checks its routing table and obtains the address of the next
gateway, G2, on the route to the datagram's internet destination
network, X.  If G2 and the host identified by the internet source
address of the datagram are on the same network, a redirect
message is sent to the host.  The redirect message advises the
host to send its traffic for network X directly to gateway G2 as
this is a shorter path to the destination.  The gateway forwards
the original datagram's data to its internet destination.
+
For datagrams with the IP source route options and the gateway
address in the destination address field, a redirect message is
not sent even if there is a better route to the ultimate
destination than the next address in the source route.
+
Codes 0, 1, 2, and 3 may be received from a gateway.
====


== Echo or Echo Reply Message

....
    0                   1                   2                   3
    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |     Type      |     Code      |          Checksum             |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |           Identifier          |        Sequence Number        |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |     Data ...
   +-+-+-+-+-
....


IP Fields: ::
+
====
[horizontal]
Addresses ::
+
The address of the source in an echo message will be the
destination of the echo reply message.  To form an echo reply
message, the source and destination addresses are simply reversed,
the type code changed to 0, and the checksum recomputed.
====

[[errata_1703]]
[.rfc-error-text]#IP Fields#: ::
+
====
[horizontal]
Type ::
+
8 for echo message;
+
0 for echo reply message.

Code ::
+
0

Checksum ::
+
The checksum is the 16-bit ones's complement of the one's
complement sum of the ICMP message starting with the ICMP Type.
For computing the checksum , the checksum field should be zero.
If the total length is odd, the received data is padded with one
octet of zeros for computing the checksum.  This checksum may be
replaced in the future.

Identifier ::
+
If code = 0, an identifier to aid in matching echos and replies,
may be zero.

Sequence Number ::
+
If code = 0, a sequence number to aid in matching echos and
replies, may be zero.

Description ::
+
The data received in the echo message must be returned in the echo
reply message.
+
The identifier and sequence number may be used by the [[errata_2935]] [.rfc-error-text]#echo sender#
to aid in matching the replies with the echo requests.  For
example, the identifier might be used like a port in TCP or UDP to
identify a session, and the sequence number might be incremented
on each echo request sent.  The echoer returns these same values
in the echo reply.
+
Code 0 may be received from a gateway or a host.
====


== Timestamp or Timestamp Reply Message

....
    0                   1                   2                   3
    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |     Type      |      Code     |          Checksum             |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |           Identifier          |        Sequence Number        |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |     Originate Timestamp                                       |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |     Receive Timestamp                                         |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |     Transmit Timestamp                                        |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
....

IP Fields: ::
+
====
Addresses ::
+
The address of the source in a timestamp message will be the
destination of the timestamp reply message.  To form a timestamp
reply message, the source and destination addresses are simply
reversed, the type code changed to 14, and the checksum
recomputed.
====

[[errata_577_1]]
[.rfc-error-text]#IP Fields#: ::
+
====
[horizontal]
Type ::
+
13 for timestamp message;
+
14 for timestamp reply message.

Code ::
+
0

Checksum ::
+
The checksum is the 16-bit ones's complement of the one's
complement sum of the ICMP message starting with the ICMP Type.
For computing the checksum , the checksum field should be zero.
This checksum may be replaced in the future.

Identifier ::
+
If code = 0, an identifier to aid in matching timestamp and
replies, may be zero.

Sequence Number ::
+
If code = 0, a sequence number to aid in matching timestamp and
replies, may be zero.

Description ::
+
The data received (a timestamp) in the message is returned in the
reply together with an additional timestamp.  The timestamp is 32
bits of milliseconds since midnight UT.  One use of these
timestamps is described by Mills <<ref5>>.
+
The Originate Timestamp is the time the sender last touched the
message before sending it, the Receive Timestamp is the time the
echoer first touched it on receipt, and the Transmit Timestamp is
the time the echoer last touched the message on sending it.
+
If the time is not available in miliseconds or cannot be provided
with respect to midnight UT then any time can be inserted in a
timestamp provided the high order bit of the timestamp is also set
to indicate this non-standard value.
+
The identifier and sequence number may be used by the [[errata_2936]] echo [.rfc-error-text]#sender#
to aid in matching the replies with the requests.  For example,
the identifier might be used like a port in TCP or UDP to identify
a session, and the sequence number might be incremented on each
request sent.  The destination returns these same values in the
reply.
+
Code 0 may be received from a gateway or a host.
====


== Information Request or Information Reply Message

....
    0                   1                   2                   3
    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |     Type      |      Code     |          Checksum             |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |           Identifier          |        Sequence Number        |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
....

IP Fields: ::
+
====
Addresses ::
+
The address of the source in a information request message will be
the destination of the information reply message.  To form a
information reply message, the source and destination addresses
are simply reversed, the type code changed to 16, and the checksum
recomputed.
====

[[errata_577_2]]
[.rfc-error-text]#IP Fields#: ::
+
====
Type ::
+
15 for information request message;
+
16 for information reply message.

Code ::
+
0

Checksum ::
+
The checksum is the 16-bit ones's complement of the one's
complement sum of the ICMP message starting with the ICMP Type.
For computing the checksum , the checksum field should be zero.
This checksum may be replaced in the future.

Identifier ::
+
If code = 0, an identifier to aid in matching request and replies,
may be zero.

Sequence Number ::
+
If code = 0, a sequence number to aid in matching request and
replies, may be zero.

   Description ::
+
      This message may be sent with the source network in the IP header
      source and destination address fields zero (which means "this"
      network).  The replying IP module should send the reply with the
      addresses fully specified.  This message is a way for a host to
      find out the number of the network it is on.
+
      The identifier and sequence number may be used by the echo sender
      to aid in matching the replies with the requests.  For example,
      the identifier might be used like a port in TCP or UDP to identify
      a session, and the sequence number might be incremented on each
      request sent.  The destination returns these same values in the
      reply.
+
      Code 0 may be received from a gateway or a host.
====

== Summary of Message Types

[horizontal]
0  :: <<_echo_or_echo_reply_message,Echo Reply>>

3  :: <<_destination_unreachable_message,Destination Unreachable>>

4  :: <<_source_quench_message,Source Quench>>

5  :: <<_redirect_message,Redirect>>

8  :: <<_echo_or_echo_reply_message,Echo>>

11  :: <<_time_exceeded_message,Time Exceeded>>

12  :: <<_parameter_problem_message,Parameter Problem>>

13  :: <<_timestamp_or_timestamp_reply_message,Timestamp>>

14  :: <<_timestamp_or_timestamp_reply_message,Timestamp Reply>>

15  :: <<_information_request_or_information_reply_message,Information Request>>

16  :: <<_information_request_or_information_reply_message,Information Reply>>


[bibliography]
== References

- [[[ref1,1]]]   Postel, J. (ed.), "Internet Protocol - DARPA Internet Program
            Protocol Specification," RFC 791, USC/Information Sciences
            Institute, September 1981.

- [[[ref2,2]]]   Cerf, V., "The Catenet Model for Internetworking," IEN 48,
            Information Processing Techniques Office, Defense Advanced
            Research Projects Agency, July 1978.

- [[[ref3,3]]]   Strazisar, V., "Gateway Routing:  An Implementation
            Specification", IEN 30, Bolt Beranek and Newman, April 1979.

- [[[ref4,4]]]   Strazisar, V., "How to Build a Gateway", IEN 109, Bolt Beranek
            and Newman, August 1979.

- [[[ref5,5]]]   Mills, D., "DCNET Internet Clock Service," RFC 778, COMSAT
            Laboratories, April 1981.


// horizontal rule
'''
'''
[frame=none, cols="^", width="99%"]
|===
| END OF THE RFC
|===
'''
'''

// it disables the section numbering
:numbered!:

== Errata

=== Verified

==== 577

====

Errata ID: https://www.rfc-editor.org/errata/eid577[577] +
Status: Verified +
Type: Technical

Reported By: Beren Sanders +
Date Reported: 2002-09-09


On p. <<errata_577_1,16>> and <<errata_577_2,18>>, it says:

[subs=+macros]
....
pass:quotes[*IP*] Fields:

Type
....

It should say:

[subs=+macros]
....
pass:quotes[*ICMP*] Fields:

Type
....

[NOTE]
=====
On page 16, the section 'Timestamp and Timestamp Reply Messages' has
the header 'IP Fields:' - first mentioned after the graph and then
again after 'Addresses'. The second one should actually be 'ICMP
Fields:'. This error also occurs in the discussion of the
'Information Request and Information Reply Message' on page 18.

The second 'IP Fields:' section of these two sets of message
descriptions are really talking about fields in the ICMP header not
the IP header.

[This report was updated 2009-03-11 to specify the original and corrected text, as indicated by Nikolai Malykh.]
=====

====

==== 576

====

Errata ID: https://www.rfc-editor.org/errata/eid576[576] +
Status: Verified +
Type: Editorial

Reported By: Arun Darlie Koshy +
Date Reported: 2004-03-26

In the Introduction, fourth paragraph, it says:

[subs=+macros]
....
Also ICMP messages are only sent about errors in handling fragment zero of
pass:quotes[*fragemented*] datagrams.  (Fragment zero has the fragment pass:quotes[*offeset*] equal
zero).
....

<<errata_576,It should say>>:

[subs=+macros]
....
Also ICMP messages are only sent about errors in handling fragment zero of
pass:quotes[*fragmented*] datagrams.  (Fragment zero has the fragment pass:quotes[*offset*] equal
zero).
....

====


=== Held for Document Update

==== 1231

====

Errata ID: https://www.rfc-editor.org/errata/eid1231[1231] +
Status: Held for Document Update +
Type: Editorial

Reported By: Stéphane Bortzmeyer +
Date Reported: 2008-01-04 +
Held for Document Update by: ron bonica

In the Introduction, it says:

[subs=+macros]
....
no ICMP messages are sent about pass:quotes[*ICMP*] messages
....

<<errata_1231,It should say>>:

[subs=+macros]
....
no ICMP messages are sent about pass:quotes[*ICMP error*] messages
....

[NOTE]
=====
For instance, echo replies are sent about echo messages. The context of the original sentence indicates that the author only referred to error messages but the sentence itself is not clear and I've seen the editorial error reproduced in some places.
=====

====

==== 1703

====
Errata ID: https://www.rfc-editor.org/errata/eid1703[1703] +
Status: Held for Document Update +
Type: Editorial

Reported By: Nikolai Malykh +
Date Reported: 2009-03-02 +
Held for Document Update by: ron bonica

On page 14, it says:

[subs=+macros]
....
   pass:quotes[*IP Fields*]:

   Type

      8 for echo message;
....

<<errata_1703,It should say>>:

[subs=+macros]
....
   pass:quotes[*ICMP Fields*]:

   Type

      8 for echo message;
....

====

==== 2935

====

Errata ID: https://www.rfc-editor.org/errata/eid2935[2935] +
Status: Held for Document Update +
Type: Editorial

Reported By: Jeffrey Connell +
Date Reported: 2011-08-13 +
Held for Document Update by: ron bonica

On page 17, it says:

[subs=+macros]
....
The identifier and sequence number may be used by the pass:quotes[*echo*] sender
to aid in matching the replies with the requests.
....

<<errata_2935,It should say>>:

[subs=+macros]
....
The identifier and sequence number may be used by the pass:quotes[*timestamp*] sender
to aid in matching the replies with the requests.
....

[NOTE]
=====
In the "Description" of the "Timestamp or Timestamp Reply" message. Appears to be a copy-paste error from the "Echo or Echo Reply" message's description.
=====

====


==== 2936

====

Errata ID: https://www.rfc-editor.org/errata/eid2936[2936] +
Status: Held for Document Update +
Type: Editorial

Reported By: Jeffrey Connell +
Date Reported: 2011-08-13 +
Held for Document Update by: ron bonica

On page 19, it says:

[subs=+macros]
....
The identifier and sequence number may be used by the pass:quotes[*echo*] sender
to aid in matching the replies with the requests.
....

<<errata_2936,It should say>>:

[subs=+macros]
....
The identifier and sequence number may be used by the pass:quotes[*information request*]
sender to aid in matching the replies with the requests.
....

[NOTE]
=====
In the "Description" of the "Information Request or Information Reply" message. Appears to be a copy-paste error from the "Echo or Echo Reply" message's description.
=====

====
